
#ifndef GL_MACRO_H
#define GL_MACRO_H
#include "../../modules/three/CWGraphicsContext.h"

// WGC3D types match the corresponding GL types as defined in OpenGL ES 2.0
// header file gl2.h from khronos.org.

#define GL_DEPTH_BUFFER_BIT               0x00000100
#define GL_STENCIL_BUFFER_BIT             0x00000400
#define GL_COLOR_BUFFER_BIT               0x00004000
#define GL_FALSE                          0
#define GL_TRUE                           1
#define GL_POINTS                         0x0000
#define GL_LINES                          0x0001
#define GL_LINE_LOOP                      0x0002
#define GL_LINE_STRIP                     0x0003
#define GL_TRIANGLES                      0x0004
#define GL_TRIANGLE_STRIP                 0x0005
#define GL_TRIANGLE_FAN                   0x0006
#define GL_ZERO                           0
#define GL_ONE                            1
#define GL_SRC_COLOR                      0x0300
#define GL_ONE_MINUS_SRC_COLOR            0x0301
#define GL_SRC_ALPHA                      0x0302
#define GL_ONE_MINUS_SRC_ALPHA            0x0303
#define GL_DST_ALPHA                      0x0304
#define GL_ONE_MINUS_DST_ALPHA            0x0305
#define GL_DST_COLOR                      0x0306
#define GL_ONE_MINUS_DST_COLOR            0x0307
#define GL_SRC_ALPHA_SATURATE             0x0308
#define GL_FUNC_ADD                       0x8006
#define GL_BLEND_EQUATION                 0x8009
#define GL_BLEND_EQUATION_RGB             0x8009
#define GL_BLEND_EQUATION_ALPHA           0x883D
#define GL_FUNC_SUBTRACT                  0x800A
#define GL_FUNC_REVERSE_SUBTRACT          0x800B
#define GL_BLEND_DST_RGB                  0x80C8
#define GL_BLEND_SRC_RGB                  0x80C9
#define GL_BLEND_DST_ALPHA                0x80CA
#define GL_BLEND_SRC_ALPHA                0x80CB
#define GL_CONSTANT_COLOR                 0x8001
#define GL_ONE_MINUS_CONSTANT_COLOR       0x8002
#define GL_CONSTANT_ALPHA                 0x8003
#define GL_ONE_MINUS_CONSTANT_ALPHA       0x8004
#define GL_BLEND_COLOR                    0x8005
#define GL_ARRAY_BUFFER                   0x8892
#define GL_ELEMENT_ARRAY_BUFFER           0x8893
#define GL_ARRAY_BUFFER_BINDING           0x8894
#define GL_ELEMENT_ARRAY_BUFFER_BINDING   0x8895
#define GL_STREAM_DRAW                    0x88E0
#define GL_STATIC_DRAW                    0x88E4
#define GL_DYNAMIC_DRAW                   0x88E8
#define GL_BUFFER_SIZE                    0x8764
#define GL_BUFFER_USAGE                   0x8765
#define GL_CURRENT_VERTEX_ATTRIB          0x8626
#define GL_FRONT                          0x0404
#define GL_BACK                           0x0405
#define GL_FRONT_AND_BACK                 0x0408
#define GL_TEXTURE_2D                     0x0DE1
#define GL_CULL_FACE                      0x0B44
#define GL_BLEND                          0x0BE2
#define GL_DITHER                         0x0BD0
#define GL_STENCIL_TEST                   0x0B90
#define GL_DEPTH_TEST                     0x0B71
#define GL_SCISSOR_TEST                   0x0C11
#define GL_POLYGON_OFFSET_FILL            0x8037
#define GL_SAMPLE_ALPHA_TO_COVERAGE       0x809E
#define GL_SAMPLE_COVERAGE                0x80A0
#define GL_NO_ERROR                       0
#define GL_INVALID_ENUM                   0x0500
#define GL_INVALID_VALUE                  0x0501
#define GL_INVALID_OPERATION              0x0502
#define GL_STACK_OVERFLOW                 0x0503
#define GL_STACK_UNDERFLOW                0x0504
#define GL_OUT_OF_MEMORY                  0x0505
#define GL_CW                             0x0900
#define GL_CCW                            0x0901
#define GL_LINE_WIDTH                     0x0B21
#define GL_ALIASED_POINT_SIZE_RANGE       0x846D
#define GL_ALIASED_LINE_WIDTH_RANGE       0x846E
#define GL_CULL_FACE_MODE                 0x0B45
#define GL_FRONT_FACE                     0x0B46
#define GL_DEPTH_RANGE                    0x0B70
#define GL_DEPTH_WRITEMASK                0x0B72
#define GL_DEPTH_CLEAR_VALUE              0x0B73
#define GL_DEPTH_FUNC                     0x0B74
#define GL_STENCIL_CLEAR_VALUE            0x0B91
#define GL_STENCIL_FUNC                   0x0B92
#define GL_STENCIL_FAIL                   0x0B94
#define GL_STENCIL_PASS_DEPTH_FAIL        0x0B95
#define GL_STENCIL_PASS_DEPTH_PASS        0x0B96
#define GL_STENCIL_REF                    0x0B97
#define GL_STENCIL_VALUE_MASK             0x0B93
#define GL_STENCIL_WRITEMASK              0x0B98
#define GL_STENCIL_BACK_FUNC              0x8800
#define GL_STENCIL_BACK_FAIL              0x8801
#define GL_STENCIL_BACK_PASS_DEPTH_FAIL   0x8802
#define GL_STENCIL_BACK_PASS_DEPTH_PASS   0x8803
#define GL_STENCIL_BACK_REF               0x8CA3
#define GL_STENCIL_BACK_VALUE_MASK        0x8CA4
#define GL_STENCIL_BACK_WRITEMASK         0x8CA5
#define GL_VIEWPORT                       0x0BA2
#define GL_SCISSOR_BOX                    0x0C10
#define GL_COLOR_CLEAR_VALUE              0x0C22
#define GL_COLOR_WRITEMASK                0x0C23
#define GL_UNPACK_ALIGNMENT               0x0CF5
#define GL_PACK_ALIGNMENT                 0x0D05
#define GL_MAX_TEXTURE_SIZE               0x0D33
#define GL_MAX_VIEWPORT_DIMS              0x0D3A
#define GL_SUBPIXEL_BITS                  0x0D50
#define GL_RED_BITS                       0x0D52
#define GL_GREEN_BITS                     0x0D53
#define GL_BLUE_BITS                      0x0D54
#define GL_ALPHA_BITS                     0x0D55
#define GL_DEPTH_BITS                     0x0D56
#define GL_STENCIL_BITS                   0x0D57
#define GL_POLYGON_OFFSET_UNITS           0x2A00
#define GL_POLYGON_OFFSET_FACTOR          0x8038
#define GL_TEXTURE_BINDING_2D             0x8069
#define GL_SAMPLE_BUFFERS                 0x80A8
#define GL_SAMPLES                        0x80A9
#define GL_SAMPLE_COVERAGE_VALUE          0x80AA
#define GL_SAMPLE_COVERAGE_INVERT         0x80AB
#define GL_NUM_COMPRESSED_TEXTURE_FORMATS 0x86A2
#define GL_COMPRESSED_TEXTURE_FORMATS     0x86A3
#define GL_DONT_CARE                      0x1100
#define GL_FASTEST                        0x1101
#define GL_NICEST                         0x1102
#define GL_GENERATE_MIPMAP_HINT           0x8192
#define GL_BYTE                           0x1400
#define GL_UNSIGNED_BYTE                  0x1401
#define GL_SHORT                          0x1402
#define GL_UNSIGNED_SHORT                 0x1403
#define GL_INT                            0x1404
#define GL_UNSIGNED_INT                   0x1405
#define GL_FLOAT                          0x1406
#define GL_FIXED                          0x140C
#define GL_DEPTH_COMPONENT                0x1902
#define GL_ALPHA                          0x1906
#define GL_RGB                            0x1907
#define GL_RGBA                           0x1908
#define GL_LUMINANCE                      0x1909
#define GL_LUMINANCE_ALPHA                0x190A
#define GL_UNSIGNED_SHORT_4_4_4_4         0x8033
#define GL_UNSIGNED_SHORT_5_5_5_1         0x8034
#define GL_UNSIGNED_SHORT_5_6_5           0x8363
#define GL_FRAGMENT_SHADER                0x8B30
#define GL_VERTEX_SHADER                  0x8B31
#define GL_MAX_VERTEX_ATTRIBS             0x8869
#define GL_MAX_VERTEX_UNIFORM_VECTORS     0x8DFB
#define GL_MAX_VARYING_VECTORS            0x8DFC
#define GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS 0x8B4D
#define GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS 0x8B4C
#define GL_MAX_TEXTURE_IMAGE_UNITS        0x8872
#define GL_MAX_FRAGMENT_UNIFORM_VECTORS   0x8DFD
#define GL_SHADER_TYPE                    0x8B4F
#define GL_DELETE_STATUS                  0x8B80
#define GL_LINK_STATUS                    0x8B82
#define GL_VALIDATE_STATUS                0x8B83
#define GL_ATTACHED_SHADERS               0x8B85
#define GL_ACTIVE_UNIFORMS                0x8B86
#define GL_ACTIVE_UNIFORM_MAX_LENGTH      0x8B87
#define GL_ACTIVE_ATTRIBUTES              0x8B89
#define GL_ACTIVE_ATTRIBUTE_MAX_LENGTH    0x8B8A
#define GL_SHADING_LANGUAGE_VERSION       0x8B8C
#define GL_CURRENT_PROGRAM                0x8B8D
#define GL_NEVER                          0x0200
#define GL_LESS                           0x0201
#define GL_EQUAL                          0x0202
#define GL_LEQUAL                         0x0203
#define GL_GREATER                        0x0204
#define GL_NOTEQUAL                       0x0205
#define GL_GEQUAL                         0x0206
#define GL_ALWAYS                         0x0207
#define GL_KEEP                           0x1E00
#define GL_REPLACE                        0x1E01
#define GL_INCR                           0x1E02
#define GL_DECR                           0x1E03
#define GL_INVERT                         0x150A
#define GL_INCR_WRAP                      0x8507
#define GL_DECR_WRAP                      0x8508
#define GL_VENDOR                         0x1F00
#define GL_RENDERER                       0x1F01
#define GL_VERSION                        0x1F02
#define GL_EXTENSIONS                     0x1F03
#define GL_NEAREST                        0x2600
#define GL_LINEAR                         0x2601
#define GL_NEAREST_MIPMAP_NEAREST         0x2700
#define GL_LINEAR_MIPMAP_NEAREST          0x2701
#define GL_NEAREST_MIPMAP_LINEAR          0x2702
#define GL_LINEAR_MIPMAP_LINEAR           0x2703
#define GL_TEXTURE_MAG_FILTER             0x2800
#define GL_TEXTURE_MIN_FILTER             0x2801
#define GL_TEXTURE_WRAP_S                 0x2802
#define GL_TEXTURE_WRAP_T                 0x2803
#define GL_TEXTURE                        0x1702
#define GL_TEXTURE_CUBE_MAP               0x8513
#define GL_TEXTURE_BINDING_CUBE_MAP       0x8514
#define GL_TEXTURE_CUBE_MAP_POSITIVE_X    0x8515
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_X    0x8516
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Y    0x8517
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Y    0x8518
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Z    0x8519
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Z    0x851A
#define GL_MAX_CUBE_MAP_TEXTURE_SIZE      0x851C
#define GL_TEXTURE0                       0x84C0
#define GL_TEXTURE1                       0x84C1
#define GL_TEXTURE2                       0x84C2
#define GL_TEXTURE3                       0x84C3
#define GL_TEXTURE4                       0x84C4
#define GL_TEXTURE5                       0x84C5
#define GL_TEXTURE6                       0x84C6
#define GL_TEXTURE7                       0x84C7
#define GL_TEXTURE8                       0x84C8
#define GL_TEXTURE9                       0x84C9
#define GL_TEXTURE10                      0x84CA
#define GL_TEXTURE11                      0x84CB
#define GL_TEXTURE12                      0x84CC
#define GL_TEXTURE13                      0x84CD
#define GL_TEXTURE14                      0x84CE
#define GL_TEXTURE15                      0x84CF
#define GL_TEXTURE16                      0x84D0
#define GL_TEXTURE17                      0x84D1
#define GL_TEXTURE18                      0x84D2
#define GL_TEXTURE19                      0x84D3
#define GL_TEXTURE20                      0x84D4
#define GL_TEXTURE21                      0x84D5
#define GL_TEXTURE22                      0x84D6
#define GL_TEXTURE23                      0x84D7
#define GL_TEXTURE24                      0x84D8
#define GL_TEXTURE25                      0x84D9
#define GL_TEXTURE26                      0x84DA
#define GL_TEXTURE27                      0x84DB
#define GL_TEXTURE28                      0x84DC
#define GL_TEXTURE29                      0x84DD
#define GL_TEXTURE30                      0x84DE
#define GL_TEXTURE31                      0x84DF
#define GL_ACTIVE_TEXTURE                 0x84E0
#define GL_REPEAT                         0x2901
#define GL_CLAMP_TO_EDGE                  0x812F
#define GL_MIRRORED_REPEAT                0x8370
#define GL_FLOAT_VEC2                     0x8B50
#define GL_FLOAT_VEC3                     0x8B51
#define GL_FLOAT_VEC4                     0x8B52
#define GL_INT_VEC2                       0x8B53
#define GL_INT_VEC3                       0x8B54
#define GL_INT_VEC4                       0x8B55
#define GL_BOOL                           0x8B56
#define GL_BOOL_VEC2                      0x8B57
#define GL_BOOL_VEC3                      0x8B58
#define GL_BOOL_VEC4                      0x8B59
#define GL_FLOAT_MAT2                     0x8B5A
#define GL_FLOAT_MAT3                     0x8B5B
#define GL_FLOAT_MAT4                     0x8B5C
#define GL_SAMPLER_2D                     0x8B5E
#define GL_SAMPLER_CUBE                   0x8B60
#define GL_VERTEX_ATTRIB_ARRAY_ENABLED    0x8622
#define GL_VERTEX_ATTRIB_ARRAY_SIZE       0x8623
#define GL_VERTEX_ATTRIB_ARRAY_STRIDE     0x8624
#define GL_VERTEX_ATTRIB_ARRAY_TYPE       0x8625
#define GL_POINT_SPRITE                   0x8861
#define GL_COORD_REPLACE                  0x8862
#define GL_VERTEX_ATTRIB_ARRAY_NORMALIZED 0x886A
#define GL_VERTEX_ATTRIB_ARRAY_POINTER    0x8645
#define GL_VERTEX_PROGRAM_POINT_SIZE      0x8642
#define GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING 0x889F
#define GL_IMPLEMENTATION_COLOR_READ_TYPE 0x8B9A
#define GL_IMPLEMENTATION_COLOR_READ_FORMAT 0x8B9B
#define GL_COMPILE_STATUS                 0x8B81
#define GL_INFO_LOG_LENGTH                0x8B84
#define GL_SHADER_SOURCE_LENGTH           0x8B88
#define GL_SHADER_COMPILER                0x8DFA
#define GL_SHADER_BINARY_FORMATS          0x8DF8
#define GL_NUM_SHADER_BINARY_FORMATS      0x8DF9
#define GL_LOW_FLOAT                      0x8DF0
#define GL_MEDIUM_FLOAT                   0x8DF1
#define GL_HIGH_FLOAT                     0x8DF2
#define GL_LOW_INT                        0x8DF3
#define GL_MEDIUM_INT                     0x8DF4
#define GL_HIGH_INT                       0x8DF5
#define GL_FRAMEBUFFER                    0x8D40
#define GL_RENDERBUFFER                   0x8D41
#define GL_RGBA4                          0x8056
#define GL_BGR                            0x80E0
#define GL_BGRA                           0x80E1
#define GL_RGB5_A1                        0x8057
#define GL_RGB565                         0x8D62
#define GL_DEPTH_COMPONENT16              0x81A5
#define GL_STENCIL_INDEX8                 0x8D48
#define GL_RENDERBUFFER_WIDTH             0x8D42
#define GL_RENDERBUFFER_HEIGHT            0x8D43
#define GL_RENDERBUFFER_INTERNAL_FORMAT   0x8D44
#define GL_RENDERBUFFER_RED_SIZE          0x8D50
#define GL_RENDERBUFFER_GREEN_SIZE        0x8D51
#define GL_RENDERBUFFER_BLUE_SIZE         0x8D52
#define GL_RENDERBUFFER_ALPHA_SIZE        0x8D53
#define GL_RENDERBUFFER_DEPTH_SIZE        0x8D54
#define GL_RENDERBUFFER_STENCIL_SIZE      0x8D55
#define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE 0x8CD0
#define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME 0x8CD1
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL 0x8CD2
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE 0x8CD3
#define GL_COLOR_ATTACHMENT0              0x8CE0
#define GL_DEPTH_ATTACHMENT               0x8D00
#define GL_STENCIL_ATTACHMENT             0x8D20
#define GL_NONE                           0
#define GL_FRAMEBUFFER_COMPLETE           0x8CD5
#define GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT 0x8CD6
#define GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT 0x8CD7
#define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS 0x8CD9
#define GL_FRAMEBUFFER_UNSUPPORTED        0x8CDD
#define GL_FRAMEBUFFER_BINDING            0x8CA6
#define GL_RENDERBUFFER_BINDING           0x8CA7
#define GL_MAX_RENDERBUFFER_SIZE          0x84E8
#define GL_INVALID_FRAMEBUFFER_OPERATION  0x0506

#define GL_DEPTH_STENCIL_OES              0x84F9
#define GL_DEPTH_STENCIL                  0x84F9
#define GL_DEPTH_STENCIL_ATTACHMENT       0x821A
#define GL_UNSIGNED_INT_24_8_OES          0x84FA
#define GL_DEPTH24_STENCIL8_OES           0x88F0

#define GL_UNPACK_FLIP_Y_WEBGL 0x9240
#define GL_UNPACK_PREMULTIPLY_ALPHA_WEBGL 0x9241
#define GL_UNPACK_COLORSPACE_CONVERSION_WEBGL 0x9243


#define   glGenBuffers                             blink::CWGraphicsContext::genBuffers
#define   glBindBuffer                             blink::CWGraphicsContext::bindBuffer
#define   glBufferData                             blink::CWGraphicsContext::bufferData
#define   glEnableVertexAttribArray                blink::CWGraphicsContext::enableVertexAttribArray
#define   glDisableVertexAttribArray               blink::CWGraphicsContext::disableVertexAttribArray
#define   glVertexAttribPointer                    blink::CWGraphicsContext::vertexAttribPointer
#define   glDrawElements                           blink::CWGraphicsContext::drawElements
#define   glDrawArrays                             blink::CWGraphicsContext::drawArrays
#define   glUniform1f                              blink::CWGraphicsContext::uniform1f
#define   glUniform1fv                             blink::CWGraphicsContext::uniform1fv
#define   glUniform1i                              blink::CWGraphicsContext::uniform1i
#define   glUniform1iv                             blink::CWGraphicsContext::uniform1iv
#define   glUniform2f                              blink::CWGraphicsContext::uniform2f
#define   glUniform2fv                             blink::CWGraphicsContext::uniform2fv
#define   glUniform2i                              blink::CWGraphicsContext::uniform2i
#define   glUniform2iv                             blink::CWGraphicsContext::uniform2iv
#define   glUniform3f                              blink::CWGraphicsContext::uniform3f
#define   glUniform3fv                             blink::CWGraphicsContext::uniform3fv
#define   glUniform3i                              blink::CWGraphicsContext::uniform3i
#define   glUniform3iv                             blink::CWGraphicsContext::uniform3iv
#define   glUniform4f                              blink::CWGraphicsContext::uniform4f
#define   glUniform4fv                             blink::CWGraphicsContext::uniform4fv
#define   glUniform4i                              blink::CWGraphicsContext::uniform4i
#define   glUniform4iv                             blink::CWGraphicsContext::uniform4iv
#define   glUniformMatrix2fv                       blink::CWGraphicsContext::uniformMatrix2fv
#define   glUniformMatrix3fv                       blink::CWGraphicsContext::uniformMatrix3fv
#define   glUniformMatrix4fv                       blink::CWGraphicsContext::uniformMatrix4fv
#define   glUseProgram                             blink::CWGraphicsContext::useProgram
#define   glCreateProgram                          blink::CWGraphicsContext::createProgram
#define   glCreateShader                           blink::CWGraphicsContext::createShader
#define   glShaderSource                           blink::CWGraphicsContext::shaderSource
#define   glCompileShader                          blink::CWGraphicsContext::compileShader
#define   glGetShaderiv                            blink::CWGraphicsContext::getShaderiv
#define   glGetShaderInfoLog                       blink::CWGraphicsContext::getShaderInfoLog
#define   glGetUniformLocation                     blink::CWGraphicsContext::getUniformLocation
#define   glGetAttribLocation                      blink::CWGraphicsContext::getAttribLocation
#define   glAttachShader                           blink::CWGraphicsContext::attachShader
#define   glBindAttribLocation                     blink::CWGraphicsContext::bindAttribLocation
#define   glLinkProgram                            blink::CWGraphicsContext::linkProgram
#define   glDeleteShader                           blink::CWGraphicsContext::deleteShader
#define   glGetIntegerv                            blink::CWGraphicsContext::getIntegerv
#define   glViewport                               blink::CWGraphicsContext::viewport
#define   glClear                                  blink::CWGraphicsContext::clear
#define   glClearColor                             blink::CWGraphicsContext::clearColor
#define   glDisable                                blink::CWGraphicsContext::disable
#define   glEnable                                 blink::CWGraphicsContext::enable
#define   glFrontFace                              blink::CWGraphicsContext::frontFace
#define   glCullFace                               blink::CWGraphicsContext::cullFace
#define   glDepthMask                              blink::CWGraphicsContext::depthMask
#define   glLineWidth                              blink::CWGraphicsContext::lineWidth
#define   glPolygonOffset                          blink::CWGraphicsContext::polygonOffset
#define   glBlendEquation                          blink::CWGraphicsContext::blendEquation
#define   glBlendEquationSeparate                  blink::CWGraphicsContext::blendEquationSeparate
#define   glBlendColor                             blink::CWGraphicsContext::blendColor
#define   glBlendFunc                              blink::CWGraphicsContext::blendFunc
#define   glBlendFuncSeparate                      blink::CWGraphicsContext::blendFuncSeparate
#define   glGenTextures                            blink::CWGraphicsContext::genTextures
#define   glActiveTexture                          blink::CWGraphicsContext::activeTexture
#define   glBindTexture                            blink::CWGraphicsContext::bindTexture
#define   glTexImage2D                             blink::CWGraphicsContext::texImage2D
#define   glGenerateMipmap                         blink::CWGraphicsContext::generateMipmap
#define   glClearDepthf                            blink::CWGraphicsContext::clearDepth
#define   glClearDepth                             blink::CWGraphicsContext::clearDepth
#define   glClearStencil                           blink::CWGraphicsContext::clearStencil
#define   glDepthFunc                              blink::CWGraphicsContext::depthFunc
#define   glGetError                               blink::CWGraphicsContext::getError
#define   glDeleteBuffers                          blink::CWGraphicsContext::deleteBuffers
#define   glDeleteTextures                         blink::CWGraphicsContext::deleteTextures
#define   glGenFramebuffers                        blink::CWGraphicsContext::genFramebuffers
#define   glDeleteFramebuffers                     blink::CWGraphicsContext::deleteFramebuffers
#define   glGenRenderbuffers                       blink::CWGraphicsContext::genRenderbuffers

#define   glBindFramebuffer                        blink::CWGraphicsContext::bindFramebuffer
#define   glBindRenderbuffer                       blink::CWGraphicsContext::bindRenderbuffer
#define   glBufferData                             blink::CWGraphicsContext::bufferData
#define   glBufferSubData                          blink::CWGraphicsContext::bufferSubData
#define   glCheckFramebufferStatus                 blink::CWGraphicsContext::checkFramebufferStatus
#define   glColorMask                              blink::CWGraphicsContext::colorMask
#define   glCompressedTexImage2D                   blink::CWGraphicsContext::compressedTexImage2D
#define   glCompressedTexSubImage2D                blink::CWGraphicsContext::compressedTexSubImage2D
#define   glCopyTexImage2D                         blink::CWGraphicsContext::copyTexImage2D
#define   glCopyTexSubImage2D                      blink::CWGraphicsContext::copyTexSubImage2D
// #define   glCreateTexture                          blink::CWGraphicsContext::createTexture
#define   glDeleteProgram                          blink::CWGraphicsContext::deleteProgram
#define   glDeleteRenderbuffers                    blink::CWGraphicsContext::deleteRenderbuffers
#define   glDepthRangef                            blink::CWGraphicsContext::depthRangef
#define   glDetachShader                           blink::CWGraphicsContext::detachShader
#define   glFinish                                 blink::CWGraphicsContext::finish
#define   glFlush                                  blink::CWGraphicsContext::flush
#define   glFramebufferRenderbuffer                blink::CWGraphicsContext::framebufferRenderbuffer
#define   glFramebufferTexture2D                   blink::CWGraphicsContext::framebufferTexture2D
#define   glGetActiveAttrib                        blink::CWGraphicsContext::getActiveAttrib
#define   glGetActiveUniform                       blink::CWGraphicsContext::getActiveUniform
#define   glGetAttachedShaders                     blink::CWGraphicsContext::getAttachedShaders
#define   glGetAttribLocation                      blink::CWGraphicsContext::getAttribLocation
#define   glGetBooleanv                            blink::CWGraphicsContext::getBooleanv
#define   glGetBufferParameteriv                   blink::CWGraphicsContext::getBufferParameteriv
#define   glGetFloatv                              blink::CWGraphicsContext::getFloatv
#define   glGetFramebufferAttachmentParameteriv    blink::CWGraphicsContext::getFramebufferAttachmentParameteriv
#define   glGetProgramiv                           blink::CWGraphicsContext::getProgramiv
#define   glGetProgramInfoLog                      blink::CWGraphicsContext::getProgramInfoLog
#define   GGetRenderbufferParameteriv              blink::CWGraphicsContext::getRenderbufferParameteriv
#define   glGetShaderPrecisionFormat               blink::CWGraphicsContext::getShaderPrecisionFormat
#define   glGetShaderSource                        blink::CWGraphicsContext::getShaderSource
#define   glGetString                              blink::CWGraphicsContext::getString
#define   glGetTexParameterfv                      blink::CWGraphicsContext::getTexParameterfv
#define   glGetTexParameteriv                      blink::CWGraphicsContext::getTexParameteriv
#define   glGetUniformfv                           blink::CWGraphicsContext::getUniformfv
#define   glGetUniformiv                           blink::CWGraphicsContext::getUniformiv
#define   glGetVertexAttribfv                      blink::CWGraphicsContext::getVertexAttribfv
#define   glGetVertexAttribiv                      blink::CWGraphicsContext::getVertexAttribiv
#define   glGetVertexAttribPointerv                blink::CWGraphicsContext::getVertexAttribPointerv
#define   glHint                                   blink::CWGraphicsContext::hint
#define   glIsBuffer                               blink::CWGraphicsContext::isBuffer
#define   glIsEnabled                              blink::CWGraphicsContext::isEnabled
#define   glIsFramebuffer                          blink::CWGraphicsContext::isFramebuffer
#define   glIsProgram                              blink::CWGraphicsContext::isProgram
#define   glIsRenderbuffer                         blink::CWGraphicsContext::isRenderbuffer
#define   glIsShader                               blink::CWGraphicsContext::isShader
#define   glIsTexture                              blink::CWGraphicsContext::isTexture
#define   glPixelStorei                            blink::CWGraphicsContext::pixelStorei
#define   glReadPixels                             blink::CWGraphicsContext::readPixels
#define   glReleaseShaderCompiler                  blink::CWGraphicsContext::releaseShaderCompiler
#define   glRenderbufferStorage                    blink::CWGraphicsContext::renderbufferStorage
#define   glSampleCoverage                         blink::CWGraphicsContext::sampleCoverage
#define   glScissor                                blink::CWGraphicsContext::scissor
#define   glShaderBinary                           blink::CWGraphicsContext::shaderBinary
#define   glStencilFunc                            blink::CWGraphicsContext::stencilFunc
#define   glStencilFuncSeparate                    blink::CWGraphicsContext::stencilFuncSeparate
#define   glStencilMask                            blink::CWGraphicsContext::stencilMask
#define   glStencilMaskSeparate                    blink::CWGraphicsContext::stencilMaskSeparate
#define   glStencilOp                              blink::CWGraphicsContext::stencilOp
#define   glStencilOpSeparate                      blink::CWGraphicsContext::stencilOpSeparate
#define   glTexImage2DHTMLImageElement             blink::CWGraphicsContext::texImage2DHTMLImageElement
#define   glTexImage2DHTMLCanvasElement            blink::CWGraphicsContext::texImage2DHTMLCanvasElement
#define   glTexImage2DHTMLVideoElement             blink::CWGraphicsContext::texImage2DHTMLVideoElement
#define   glTexParameterf                          blink::CWGraphicsContext::texParameterf
#define   glTexParameterfv                         blink::CWGraphicsContext::texParameterfv
#define   glTexParameteri                          blink::CWGraphicsContext::texParameteri
#define   glTexParameteriv                         blink::CWGraphicsContext::texParameteriv
#define   glTexSubImage2D                          blink::CWGraphicsContext::texSubImage2D
#define   glValidateProgram                        blink::CWGraphicsContext::validateProgram
#define   glVertexAttrib1f                         blink::CWGraphicsContext::vertexAttrib1f
#define   glVertexAttrib1fv                        blink::CWGraphicsContext::vertexAttrib1fv
#define   glVertexAttrib2f                         blink::CWGraphicsContext::vertexAttrib2f
#define   glVertexAttrib2fv                        blink::CWGraphicsContext::vertexAttrib2fv
#define   glVertexAttrib3f                         blink::CWGraphicsContext::vertexAttrib3f
#define   glVertexAttrib3fv                        blink::CWGraphicsContext::VertexAttrib3fv
#define   glVertexAttrib4f                         blink::CWGraphicsContext::vertexAttrib4f
#define   glVertexAttrib4fv                        blink::CWGraphicsContext::vertexAttrib4fv

#endif
