// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    GarbageCollected,
    NoInterfaceObject
] interface Three {    
    void forceGC();
    void init(WebGLRenderingContext context, long width, long height);
    void run();
    void step(double dt);
};
